# Site settings
title: MINDPIN TEAM
description: 我们是一个轻型快速反应团队；我们正在持续努力开发简洁的工具和有趣的内容；
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mindpin.com" # the base hostname & protocol for your site

encoding: UTF-8

# github 风格 markdown
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

# 以 _miniwiki 文件夹作为词条资源文件夹
collections: 
  works:
    output: true